# fly.toml file generated for nalka-on-pitka-api on 2022-10-05T17:54:02+03:00

app = "nalka-on-pitka-api"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[env]
  PHX_HOST = "nalka-on-pitka-api.fly.dev"
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
